### PR TITLE
feat: added the navigation component

### PR DESCRIPTION
**Pull request by pradipgharge**
added navigation & updated readme

### CODE REVIEW

**Review by sri-rishi — APPROVED** [review]
Great work, UI and Code looks good to me

**Review by sainath7878 — APPROVED** [review]
Everything looks good. Good that you've used semantic HTML for navbar. Great work!

**Review by anasm11 — APPROVED** [review]
Great UI. Looks good to merge.

**Review by mehulsatardekar — APPROVED** [review]
@pradipgharge all looks good you can merge this branch

**Pull request merged**
