### PR TITLE
feat: added avatar component

### PR DESCRIPTION
**Pull request by pradipgharge**
made avatar components and refactored previous code.

### CODE REVIEW

**Comment by swstica** [comment]
looks good to me!! Can be merged.

**Review by Mohitk391 — APPROVED** [review]
Looks good...can be merged!! great work brother..keep it up..

**Comment by Sahil25061999** [comment]
looks good no changes required can be merged.

**Review by manish-GH — APPROVED** [review]
Nice choice of images for avatars. Looks really good.

Just a suggestion, for the sidebar you could add position sticky

**Comment by pradipgharge** [comment]
> Nice choice of images for avatars. Looks really good.
> 
> Just a suggestion, for the sidebar you could add position sticky

I tried doing that for a long time, couldn't achieve the result!  Will add that in later versions. Thanks for the suggestion though!

**Pull request merged**
